### ISSUE TITLE
xrbase cant be found on ue 5.2 and the project fails to start. 

### ISSUE THREAD

**Issue by jerobarraco** [demonixis/FSOpenXRHandTracking#1]
https://github.com/demonixis/FSOpenXRHandTracking/blob/943dbd7467446b77f88ce8d66878a9f3d7157405/Source/FSOpenXRHandTracking/FSOpenXRHandTracking.Build.cs#L16

**Comment by demonixis** [comment]
Hello,
Thanks for the report, as indicated into the README, it's only tested on 5.3. You can probably compile the plugin without XRBase because it's a refactor from 5.3. I've no plans to support older version of Unreal but feel free to submit a pull request.

**Comment by jerobarraco** [comment]
Thanks a lot 👍 i understand.
a bit sad since i'm stuck with 5.2.
i did managed to get it compiling, though still haven't been able to make it work.
Great work anyways.
